stages:
  Data_Collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  Data_Preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    outs:
    - data/processed
  Model_Training:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    outs:
    - model.pkl
