stages:
  Data_Collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  Data_Preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    outs:
    - data/processed
